### ISSUE TITLE
BarChartView Data property is readonly

### ISSUE THREAD

**Issue by cprieto** [Flash3001/iOSCharts.Xamarin#10]
How should I fill the data for a BarChartView? I explored the assembly and the definition in your source code and it is readonly, is this normal compared with previous versions?

I checked MPAndroidCharts and iOS charts, the data setter works, in fact, the Android version for the Nuget package has a setter for Data.

Thanks a lot for your hard work!

**Comment by Flash3001** [comment]
There is a (I suppose) bug in Xamarin that causes some members to be hidden (using new) when implementing a protocol that has already been implemented (a base protocol from a derived protocol). I've put a sample here: https://forums.xamarin.com/discussion/72120/protocol-inline-hides-inherited-member-on-lvl3-inheritance#latest
(sorry, not able to find the right sentence and words to explain the problem).

And I forgot about it when redoing all the work for version 3.0. I'll fix it and send an update. 

Meanwhile you can cast it to a base class and set the Data from there:

`(yourChart as ChartViewBase).Data = yourData;`

**Comment by Flash3001** [comment]
Done!

**Comment by cprieto** [comment]
Thanks @Flash3001 ! I am closing this thread right now.
