### ISSUE TITLE
ITMS-90668: Incomplete bitcode since V3

### ISSUE THREAD

**Issue by jamie94bc** [Flash3001/iOSCharts.Xamarin#13]
We're getting this error since updating to V3 of the library - same as #4 

Running `otool -l -arch armv7 Charts | grep LLVM` against a clone of this repo confirms the library contains bitcode.

**Comment by Flash3001** [comment]
Ops! I'm sorry @jamie94bc 

I forgot to include the -arch when first checking for Bitcode, just pushed an update to NuGet.
