### ISSUE TITLE
iOSChars version 3.0.1 error

### ISSUE THREAD

**Issue by daniel-fusco** [Flash3001/iOSCharts.Xamarin#16]
Hi Lucas.

I'm trying to use iOSChars version 3.0.1, but my app crashes whenever I start the simulator, showing the following error:

Could not register the selector 'stringForValue:axis:' of the member 'iOSCharts.ChartIndexAxisValueFormatter.StringForValue' because the selector is already registered on the member 'Axis'.

The chart I'm trying to use is _TtC6Charts12PieChartView.

Could you please give me a hand?

Thanks.

**Comment by Flash3001** [comment]
@daniel-fusco Thanks for reporting this. 

Bug has being fixed! Just sent an update to NuGet.
