### ISSUE TITLE
No setter for AxisDependency in data sets

### ISSUE THREAD

**Issue by gaudecker** [Flash3001/iOSCharts.Xamarin#18]
They seem to be missing from at least `BarChartDataSet` and `LineChartDataSet`. Is there any other way to set axis dependencies?

**Comment by Flash3001** [comment]
@gaudecker Version 3.0.2 has been released, along with it the AxisDependency setter for the DataSets were added. 

I believe you can use the property by casting the DataSet to it's base class.

There's an issue with Xamarin related to overriding some properties when an interface is reapplied to a class, hiding the base one. You can check a check the full description of the problem in this bug report: https://bugzilla.xamarin.com/show_bug.cgi?id=46812

While this issue isn't fixed I need to re-add the property to the final class or to the interface itself. 

Thanks for reporting, if you find others like this let me know. I'm adding them by demand.

**Comment by gaudecker** [comment]
Thank you, this is much appreciated! ❤️
