### ISSUE TITLE
Issues with uploading to AppStore that includes Chart framework

### ISSUE THREAD

**Issue by kevinlcfei** [Flash3001/iOSCharts.Xamarin#2]
So I am having an issue uploading my app to the app store. Everything is fine when it validates and verifies fine without errors, but when I try to upload the binary I get numerous errors. Here are the ones for Charts.

Error Messages:
        ERROR ITMS-90035: "Invalid Signature. A sealed resource is missing or invalid. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftContacts.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftCore.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftCoreGraphics.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftCoreImage.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftDarwin.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftDispatch.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftFoundation.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftObjectiveC.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'XilnexOTM.iOS.app/Frameworks/Charts.framework/Frameworks/libswiftUIKit.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
        ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XilnexOTM.iOS.app/Frameworks/Charts.framework' contains disallowed file 'Frameworks'."

Please advise this issue.
- Set Deployment target: 8.0

**Comment by deepakthumbmunkeys** [comment]
@kevinlcfei : did you find the solution?? actually I'm facing the same problem too

Deployement target : 9.0

**Comment by Flash3001** [comment]
I'm making some changes to it. I believe it will work. There's no information from Xamarin on how to properly bind a Framework based on Swift. 

I'll notify you when it gets pushed to NuGet. 

Please give me a feedback on it. 

I couldn't notice this error before because my app wasn't pushed to AppStore yet.

**Comment by kevinlcfei** [comment]
@deepakthumbmunkeys Nope. cannot resolved this issue yet. Still googling the solution. 

@Flash3001 Ya sure. Will try on the new release version. Let us know about it. 
Thanks for your reply.

**Comment by Flash3001** [comment]
@kevinlcfei @deepakthumbmunkeys 
Please give it a try now. I updated the NuGet pack.
2.2.3.6

**Comment by kevinlcfei** [comment]
Hi Flash,

Good news! Try to release the apps with latest version of iOSCharts, it solved the issue. 
However, it occurs new issue in the project. Not sure wanna post under this issue or create new issue post? 

if **Linker behavior: Link Framework SDKs only**, will prompt error out.

> MTOUCH: Error MT2002: Failed to resolve "System.Void ObjCRuntime.DelegateProxyAttribute::.ctor(System.Type)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065" (MT2002)

else if **Linker behavior: Don't Link**, this setting works to create ipa via application loader and submit to AppStore.

I have no idea what wrong here? Did your project Xamarin.iOS version is 0.0.0.0?

![image](https://cloud.githubusercontent.com/assets/1302912/15387204/5f478824-1dde-11e6-8d03-0430409ca5df.png)

Edited:
Found out some information for the issue.

> I've got the same problem with a nuget package I wanted to use.
> 
> I think this means that the package has been built with the beta release of Xamarin.iOS 9.8, as DelegateProxyAttribute is listed as a new type in the API changes page:
> 
> ( https://developer.xamarin.com/releases/ios/api_changes/from_9.6.0_to_9.8.0/)

**Comment by deepakthumbmunkeys** [comment]
@Flash3001 
I'm getting the same issue here. Using iOS-Charts (ver2.2.3.6) from Nuget.

error MT2002: Failed to resolve "System.Void ObjCRuntime.DelegateProxyAttribute::.ctor(System.Type)" reference from "Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065"

@kevinlcfei  if you find any solution for this issue please let me know

**Comment by Flash3001** [comment]
@kevinlcfei That seems to be the case, I've built it using the alpha channel. 

A different problem has emerged for me: When I try to upload my app to AppStore it says: "Invalid Swift Support - The SwiftSupport folder is missing."

I'm trying to fix it in here. 

As for the "error MT2002: Failed to resolve..." I'll just go back to the stable channel, recompile and send it to NuGet.

**Comment by Flash3001** [comment]
@kevinlcfei @deepakthumbmunkeys 
I've just updated the library on Nuget. It should remove the linking error.

**Comment by Flash3001** [comment]
@kevinlcfei @deepakthumbmunkeys 
I managed to publish my App and the binary was validated.

When creating the IPA for publish you might get the following error:

"Invalid Swift Support - The file libswiftContacts.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftContacts.dylib."

The following script will help: https://github.com/bq/ipa-packager

You shall create IPA using the usual tecnique, extract it.
Then you need to run the script passing your app (already signed) inside the 'Payload' folder as an argument.
The second argument is the name of the new IPA file.

**Comment by kevinlcfei** [comment]
@Flash3001 
While submitting the apps to AppStore did not encounter the Invalid Swift Support error.
Work like a charm.

Thanks for your reply. 
And will be closing this issue.

**Comment by volcano619** [comment]
This seems to be happening with the latest version as well, any workaround ??

**Comment by dkok** [comment]
> @Flash3001
> While submitting the apps to AppStore did not encounter the Invalid Swift Support error.
> Work like a charm.
> 
> Thanks for your reply.
> And will be closing this issue.

Having this issue again with the latest version. The ipa-packager does not change anything about this. Any ideas?
