### ISSUE TITLE
Graph is being drawn outside of visible area

### ISSUE THREAD

**Issue by daffodilistic** [Flash3001/iOSCharts.Xamarin#20]
![](http://i.imgur.com/ntTBxZ5)

Hi,

I'm using the charts library as a custom renderer in a PCL project. As seen in this screenshot, the render area for the line chart seems to be drawn offscreen. Before data is loaded however, the text saying "No data is available" is shown.

The pie chart and bar chart are also exhibiting this "offscreen drawing" behavior as well. Am I coding the custom renderer wrongly somewhere?

**Comment by Flash3001** [comment]
@daffodilistic This issue is related to the original library, you can try opening an issue in https://github.com/danielgindi/Charts

**Comment by daffodilistic** [comment]
Okay, will close this and open one on "upstream"

**Comment by daffodilistic** [comment]
Coming back to this issue, this is easily fixed by calling `nativeChart.ViewPortHandler.SetChartDimensWithWidth(this.Frame.Width - 5, this.Frame.Height - 5)` for the line chart, at least. Untested on other charts.
