### ISSUE TITLE
Legend text size on a  pie chart ?

### ISSUE THREAD

**Issue by PicTrbd** [Flash3001/iOSCharts.Xamarin#21]
Hi,

First, thanks for making charts compatible with Xamarin iOS.

I was looking into the doc of the original chart lib and I noticed a function "setTextSize(float size)", allowing the user to set the font size of the legend.

I tried to do so on my PieChart on iOS but I never managed to find the function which would allow me to do so. Is there one ?

Regards,

**Comment by Flash3001** [comment]
@Pictar where did you find this code? 

Didn't try it in here, but you could try something like
`_chart.Legend.Font = _chart.Legend.Font.WithSize(18);`

http://stackoverflow.com/a/28847915/1698917

**Comment by PicTrbd** [comment]
Works well, thanks !
