### ISSUE TITLE
Highlight Arrow on a BarChart

### ISSUE THREAD

**Issue by PicTrbd** [Flash3001/iOSCharts.Xamarin#22]
Hi Flash,

I was looking to the MPAndroidChart documentation at https://github.com/PhilJay/MPAndroidChart/wiki/Specific-Chart-Settings-&-Styling

I imagine the "setDrawHighlightArrow(boolean enabled)" function is supposed to draw the value above the bar of a Bar Chart when selected (highlighted), like in the example.

<img width="878" alt="capture d ecran 2017-04-19 a 15 01 12" src="https://cloud.githubusercontent.com/assets/5642493/25181203/0cca3390-2511-11e7-99c2-349fe0db3ca6.png">

However I can't find an equivalent for the DrawHighlightArrow function. Is there any ?

**Comment by Flash3001** [comment]
@Pictar I believe this method was removed on version 3.0, you can't find it in the source code anymore https://github.com/PhilJay/MPAndroidChart/search?utf8=%E2%9C%93&q=setDrawHighlightArrow&type=

You can see a "Major refactoring of the Highlight mechanism." in the v3.0 changelog https://github.com/danielgindi/Charts/releases/tag/v3.0.0

Most other things you can find as properties in the C# binding for the iOS version as in:
`bool AutoScaleMinMaxEnabled { get; set; }`
