### ISSUE TITLE
Issue with iPad deploy

### ISSUE THREAD

**Issue by flashfoxter** [Flash3001/iOSCharts.Xamarin#23]
Launched application 'com.x.x’ on ‘x’s iPad' with pid 233
dyld: Library not loaded: @rpath/libswiftCore.dylib
Referenced from: /private/var/containers/Bundle/Application/EEF1ADBE-7D7A-Application 'com.x.x' terminated.
4A11-9693-1A594AF4495C/x.iOS.app/Frameworks/Charts.framework/Charts
Reason: no suitable image found. Did find:
/private/var/containers/Bundle/Application/EEF1ADBE-7D7A-4A11-9693-1A594AF4495C/x.iOS.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/EEF1ADBE-7D7A-4A11-9693-1A594AF4495C/x.iOS.app/Frameworks/libswiftCore.dylib'

Xamarin Studio Community 6.3 (build 863)
Stable channel
Xcode Version 8.3.2 (8E2002)

**Comment by Flash3001** [comment]
@flashfoxter Sorry for the HUGE delay. Did you manage it? Is it happening only to iPad not iPhone? 

I've only now seen you commented on this https://github.com/Flash3001/iOSCharts.Xamarin/issues/17 closed issue. 

In your case, it is happening only on the second build as well? A clean/rebuild fix it?

**Comment by follesoe** [comment]
Clean/rebuild is still the way I have to do it in order to build Relese or Debug on physical device. If I have built once, I have to clean to run it a second time. A huge pain as the build times are really slow when building from scratch every time...

**Comment by Flash3001** [comment]
@flashfoxter @follesoe are you still having this issue after the most recent updates to Xamarin Studio?

**Comment by vorotnyaknazar** [comment]
@Flash3001 I have the same issue (not with iOSCharts, but with the same approach from your article of binding swift libraries). It doesn't matter iPad or iPhone. full rebuild signs all *dylibs but when you change anything and try to debug it crashes on startup because this time target _CodesignNativeLibraries isn't executed at all
I created an issue here https://github.com/xamarin/xamarin-macios/issues/4610

**Comment by Flash3001** [comment]
Hey @vorotnyaknazar @follesoe and @flashfoxter, on May, 2017 I spent some time trying to debug it on VS and didn't have any success reproducing it, but when I read @vorotnyaknazar report I saw the **Version 15.7.6** and realized the issue you are having is not on VS4M, but on the VS for Windows! It didn't cross my mind back then. I'm sorry!

I was able to reproduce it and hack it to work. I won't publish it on Nuget for now as I didn't test it much, if you can test it for a few days and tell me if it doesn't break anything else it would be really nice =) 

Please replace the contents of Xamarin.Swift4.targets for the lines bellow - it will resign the Swift dylibs on every compilation (as VS does for the app itself).

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <UsingTask TaskName="Microsoft.Build.Tasks.Copy" Condition="$(OS) == 'Windows'" AssemblyFile="Xamarin.iOS.Tasks.dll"/>
  <UsingTask TaskName="Microsoft.Build.Tasks.RemoveDir" Condition="$(OS) == 'Windows'"  AssemblyFile="Xamarin.iOS.Tasks.dll"/>
  <UsingTask TaskName="Microsoft.Build.Tasks.Delete" Condition="$(OS) == 'Windows'" AssemblyFile="Xamarin.iOS.Tasks.dll"/> 
  <PropertyGroup Condition="'$(Platform)' == 'iPhoneSimulator'">
    <CreateAppBundleDependsOn>
	$(CreateAppBundleDependsOn);
      	_CopySwiftLibsSimulator;
	</CreateAppBundleDependsOn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)' == 'iPhone'">
    <_CompileToNativeDependsOn>
      _RemoveExtraLibs;
      $(_CompileToNativeDependsOn);
    </_CompileToNativeDependsOn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Platform)' == 'iPhone'">
    <_CoreCodesignDependsOn>
      _CodesignSwift;
      $(_CoreCodesignDependsOn);
    </_CoreCodesignDependsOn>
  </PropertyGroup>
  
  <Target Name="_CopySwiftLibsSimulator">
    <ItemGroup>
        <_SwiftLibsSimulator Include="$(_AppBundlePath)SwiftFrameworksSimulator\libswift*.dylib" />
    </ItemGroup>
    <ItemGroup>
        <_SwiftLibsDevice Include="$(_AppBundlePath)Frameworks\libswift*.dylib" />
    </ItemGroup>
    <Delete SessionId="$(BuildSessionId)" Files="@(_SwiftLibsDevice)" />
    <Copy SessionId="$(BuildSessionId)" SourceFiles="@(_SwiftLibsSimulator)" DestinationFolder="$(_AppBundlePath)Frameworks" />
  </Target>

  <Target Name="_CodesignSwift">
    <ItemGroup>
        <_SwiftLibsDevice Include="$(_AppBundlePath)Frameworks\libswift*.dylib" />
    </ItemGroup>

    <PropertyGroup>
      <_CodesignDisableTimestamp>False</_CodesignDisableTimestamp>
    </PropertyGroup>

    <Codesign
      SessionId="$(BuildSessionId)"
      Condition="'$(IsMacEnabled)' == 'true'"
      ToolExe="$(CodesignExe)"
      ToolPath="$(CodesignPath)"
      CodesignAllocate="$(_CodesignAllocate)"
      DisableTimestamp="$(_CodesignDisableTimestamp)"
      Keychain="$(CodesignKeychain)"
      Resources="@(_SwiftLibsDevice)"
      SigningKey="$(_CodeSigningKey)"
      ExtraArgs="$(CodesignExtraArgs)" >
    </Codesign>
	</Target>

  <Target Name="_RemoveExtraLibs">
    <RemoveDir SessionId="$(BuildSessionId)" Directories="$(_AppBundlePath)SwiftFrameworksSimulator" />
  </Target>
</Project>
```

I wouldn't call it a final solution, but it should work as a workaround while we learn what is happing on VS side.

**Comment by vorotnyaknazar** [comment]
@Flash3001 Thanks, Most likely I will test it today

UPDATE: it's working for me
