### ISSUE TITLE
ERROR ITMS-90017

### ISSUE THREAD

**Issue by avjiang** [Flash3001/iOSCharts.Xamarin#25]
Hi, I am using Xcode 8 and I have followed your instruction to use the ipa packager for it

###For Swift 2.3 run the script: sh package_ipa_xcode8_swift23.sh /path/to/signed/app /output/ipa/path

Example of my script path 

sh package_ipa_xcode8_swift23.sh /Users/user/Library/Developer/Xcode/Archives/2017-05-31/ /Users/user/Desktop/NewApp.ipa

the script above gives me NewApp.ipa. However when i want to upload it to AppStore, it gives me this error 

ERROR ITMS-90017: "This bundle is invalid. The IPA format requires a top-level directory named Payload, containing only a .app bundle and optional plugins in a Plugins directory."

The process I undergo is : 
1. Xamarin Studio -> Archive for Publishing
2. Sign and Distribute -> Select option 2 -> Save to disk and open Application Loader
3. Run the IPA Packager Script to the signed archive. Produce new IPA package
4. Upload the newly created IPA Package to the App Store by Application Loader
5. Error pops up

FYI, I didn't update the Charts to v3 yet.

What am I missing here? Really need your help :)

Thanks!

**Comment by Flash3001** [comment]
Hey @avjiang between step 2 and 3 you should extract you Archive IPA after you save it to disk.

Then you run the script with something like:
 
sh package_ipa_xcode8_swift23.sh /Users/user/Library/Developer/Xcode/Archives/2017-05-31/**MyPackage.app** /Users/user/Desktop/NewApp.ipa

**Comment by avjiang** [comment]
Hi Flash,

Sorry if I am asking too much since I am newbie to this
I have run the script for the extracted .app from the IPA package (I change the IPA package to .zip first then extract it).

I need to tell you that this is how I run the script. After I downloaded your package in zip file, i extract it to my download folders. then I open the terminal ( Mac OS ), then I cd to the package directory like this  
1. cd /Users/user/Downloads/ipa-packager-master
2. sh package_ipa_xcode8_swift23.sh /Users/user/Desktop/Payload/OriginalApp.app /Users/user/Desktop/NewApp.ipa

The new IPA consists of this result ( After I change it to .zip )
2 Folders:
A. Payload -> MyApp
B. SwiftSupport -> Nothing inside

My Process is : 
1. Xamarin Studio -> Archive for Publishing
2. Sign and Distribute -> Select option 2 -> Save to disk and open Application Loader
3. I change the newly created IPA package to .zip and then extract it.
4. Go into payload -> and there is my App. 
5. Run the script to this .app file
6. Produces me new IPA with 2 folders inside, but the SwiftSupport folder is empty

I am still receiving the Invalid Swift Support error from Apple.

What is wrong? I really need your help since I have to release it :) and your help will be a life saver! Thanks!

*UPDATE*

I look at the script report, I have this following error

cp: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphoneos/Charts.framework: No such file or directory
Copying libswiftContacts.dylib
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphoneos/libswiftContacts.dylib: No such file or directory
Copying libswiftCore.dylib
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphoneos/libswiftCore.dylib: No such file or directory
Copying libswiftCoreBluetooth.dylib
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreBluetooth.dylib: No such file or directory
Copying libswiftCoreGraphics.dylib
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreGraphics.dylib: No such file or directory
Copying libswiftCoreImage.dylib
cp: /Applications/Xcode.app/Contents/Developer/Toolchains/Swift_2.3.xctoolchain/usr/lib/swift/iphoneos/libswiftCoreImage.dylib: No such file or directory

*In the end of the Script*
adding: SwiftSupport/	(in=0) (out=0) (stored 0%)
total bytes=105018084, compressed=40644541 -> 61% savings

I thought it might give you some idea on what is really happening here? My Xcode version is 8.3.2

**Comment by Flash3001** [comment]
Hey @avjiang I'm sorry, the important thing has skipped my eyes.

XCode 8.3.2 doesn't have support for Swift 2.3. XCode 8.2.1 did.

You got two options:

- Run the script in a computer with XCode 8.2.1 or downgrade back to it.
- Update your code for V3.

There're some breaking changes from V2 to V3, but for the project I work on it took very few time to change. 

You can find a list of changes in here: https://github.com/danielgindi/Charts/releases/tag/v3.0.0

**Comment by avjiang** [comment]
Hi Flash, 

The script now gives me SwiftSupport folder with files inside. 

However, I am still receiving Invalid Swift Support. It says that the files inside the SwiftSupport folder don't match with all those swift lib files inside Payload->MyApp->Frameworks. 

Any idea on what's going on? I am using the Xcode 8.2.1 already

**Comment by Flash3001** [comment]
@avjiang What are the exactly version of Xamarin.Swift23.Support  and iOSCharts you're using?

The iOSCharts compatible with Swift 2.3 was only released in pre-release on NuGet. 

You will need these two packages installed:

https://www.nuget.org/packages/iOSCharts/2.2.5.2-xcode8
https://www.nuget.org/packages/Xamarin.Swift23.Support/2.3.2.2

This 2.3.2.2 release of Xamarin.Swift23.Support is compatible with the XCode 8.2.1
