### ISSUE TITLE
Invalid Swift Support - The file libswiftCore.dylib doesn’t have the correct code signature.

### ISSUE THREAD

**Issue by EugeneUr** [Flash3001/iOSCharts.Xamarin#27]
Hi @Flash3001 ,

I was able to submit an App a few weeks ago, using this nuget, without an error but now i can't make it go away and i am wondering if this is somehow related to upgrading xcode to "Version 8.3.3 (8E3004b)"? or maybe Xamarin Studio not being updated to support that xcode version. I am creating the SwiftSupport folder and this is the only .dll its complaining about.

The full error message from Apple:
Invalid Swift Support - The file libswiftCore.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftCore.dylib.

Upgrading everything to 3.1.02 also didn't help.

Any advise and help is greatly appreciated :)

Thanks!

**Comment by EugeneUr** [comment]
Managed to fix it somehow... 

1. I deleted the package, obj, and bin folder. 
2. Restored the nuget, using your latest official version 3.0.1 and 3.1.0. 
3. Used Xamarin Studio to archive.
4. From XCode, i open the archive and created the SwiftSupport folder and copied all the swift.dlls into it
5. Exported the archive with XCode.
6. Uploaded with application loader

Hope it helps someone.

**Comment by abram-lincol** [comment]
EugeneUr, 
What dlls do you copy to SwiftSupport folder?
Xamarin.SwiftN.* ? Or libswift*.dylib?

Thanks!

**Comment by EugeneUr** [comment]
Hey @Abramovalekcei ,

You want to to copy the libswift*.dylib files.

The other thing you need to make sure happens is that your NuGet packages, for the swift libraries, are the same version as your XCode. Otherwise, you will get an error during submission about them being signed incorrectly. @Flash3001 is really good at updating the swift libraries right after an XCode update and usually that only requires changing those libraries and not the iOSChart version, so watch out for that in visual studio.

**Comment by Nininea-zz** [comment]
Hello @EugeneUr  

I have the same problem, did all the steps you described.  Here is how myapplication.xcarchive looks:

 
<img width="593" alt="screen shot 2018-01-30 at 8 54 51 pm" src="https://user-images.githubusercontent.com/6938188/35579367-eed5bb72-05ff-11e8-8b38-91400c2e85d4.png">


But got email :
Invalid Swift Support - The file libswiftCore.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftCore.dylib.

I send almost 4 hours to update new build :(

**Comment by Flash3001** [comment]
When sending the app to Apple they require you IPA to contain 2 copies of each Swift library. 

1 - One contained inside of Payload/NAME.app/Frameworks/libswift*.dylib
2 - Another one contained inside of SwiftSupport/libswift*.dylib

The first one has to be signed using your signing key.
The second one can't be signed by you! It must be the exact same version as the first one, but exactly as it came with Xcode.

It means that if you copy the ones in .../Frameworks to SwiftSupport your app will be reject because of "doesn't have the correct code signature".

The first set of libraries is provided for you by this project. Just add it and it will work with Xamarin compilation process, including code sign. 

The second set of libraries can be added manually by copying it from the Xcode folder or by running a script like this one: https://github.com/bq/ipa-packager

**Comment by Nininea-zz** [comment]
@Flash3001  thanks for fast response. 

Second part is bit unclear: 

"The second set of libraries can be added manually by copying it from the Xcode folder or by running a script like this one: https://github.com/bq/ipa-packager"


How do you mean copying it from Xcode folder?  

I see myapplication> obj>Xcode>0 folder but there are not any .dylib files

**Comment by Nininea-zz** [comment]
I also tried to sign package with following script :  https://github.com/jamesbar2/auto-ipa-packager

but got exception while uploading file  :  
 ERROR ITMS-90046: "Invalid Code Signing Entitlements. Your application bundle's signature contains code signing entitlements that are not supported on iOS. Specifically, value 'development' for key 'aps-environment' in 'Payload/myapp.iOS.app/myapp.iOS' is not supported."  :((

**Comment by Flash3001** [comment]
@Nininea When you install Xcode it comes with all Swift libraries for the latest version with it. There is a folder called **Xcode.app/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/** containing all original files.

About the new error message. I'm not sure it is related to the Swift libraries. How are you archiving your app to publication in Xamarin? When you are about to publish your app by clicking **Archive for Publishing** and then **Sign and Distribute** it generates a **MyApplication.IPA**, not a MyApplication.xcarchive

Please read step 7 here: https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76

**Comment by Nininea-zz** [comment]
@Flash3001  @EugeneUr  
Please take a look . 

Here are steps what I did, regarding comments on this issue :

1. build the application in release
2. Archive for publishing 
3. right click to archive -> reveal in finder -> right click to xcarchive -> show package content  and create 'SwiftSupport' folder here 
4. Go to : /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift
copied  all 15 swift library framework uses .
5. Open xcode -> archives -> export myapp (App Store)  get myapp.ipa file 
6. Open Application loader , choose myapp.ipa and upload 

and now I get : Invalid Swift Support - The file .DS_Store doesn’t have a signing ID. Sign the file, rebuild your app using the current public (GM) version of Xcode, and resubmit it.  :////

**Comment by EugeneUr** [comment]
@Nininea 

i think you are copying all your files blindly, are you using a cp * command? the .DS_Store file is usually used by git.

**Comment by Flash3001** [comment]
@Nininea I have never published an App using the approach you use so I can't tell how it would work, but you can try to replace your step 3 and forward with:

3. Right click and select **Sign and Distribute**
4. Right click the exported IPA and select `Extract` (a folder called Payload will show)
5. Run https://github.com/bq/ipa-packager script with the input being path the YourApp.app just extracted (inside the Payload folder) and the output being the path and name of the new IPA to be created.
6. This step is the same thing you do now.

**Comment by SureshChary** [comment]
@Nininea  I got the same issue now (.DS_Store doesn’t have a signing ID). Did you fix it?

**Comment by nadalizadeh** [comment]
.DS_Store is a file created by Finder when you open that folder. It should not exists in your final ipa package.

the ipa package is actually a zip file, rename it to have a zip extension, and remove that .DS_Store extra file you have created or use terminal commands to copy such as "cp -v sourcePath/lib*.dylib destinationFolder"

**Comment by pwhsueh** [comment]
I cannot  submit an App to App Store. The full error message from Apple:

ITMS-90428: Invalid Swift Support - The files libswiftFoundation.dylib, libswiftQuartzCore.dylib, libswiftos.dylib, libswiftCoreFoundation.dylib, libswiftDispatch.dylib, libswiftCoreImage.dylib, libswiftMetal.dylib, libswiftUIKit.dylib, libswiftObjectiveC.dylib, libswiftDarwin.dylib, libswiftCoreGraphics.dylib, libswiftCore.dylib don’t match /Payload/UnsignAppDemo.app/Frameworks/libswiftFoundation.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftQuartzCore.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftos.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftDispatch.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCoreImage.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftMetal.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftUIKit.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftObjectiveC.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftDarwin.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCore.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/UnsignAppDemo.app/Frameworks/libswiftFoundation.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftQuartzCore.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftos.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftDispatch.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCoreImage.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftMetal.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftUIKit.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftObjectiveC.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftDarwin.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/UnsignAppDemo.app/Frameworks/libswiftCore.dylib.

Any advise and help is greatly appreciated :)

Thanks!

**Comment by nadalizadeh** [comment]
The version of swift libraries you put in the **SwiftSupport** folder in **Payload** folder of IPA file should be exactly the same version you put in your **Frameworks** folder, **except that it should not be signed**.

1. You can check the differences using the "file" command to see what architectures does your library include in SwiftSupport and in Frameworks
```
file Payload/UnsignAppDemo.app/Frameworks/libswiftUIKit.dylib
file SwiftSupport/iphoneos/libswiftUIKit.dylib
```
and compare the output.

2. to check their versions use otool -l:
```
otool -l Payload/UnsignAppDemo.app/Frameworks/libswiftUIKit.dylib | grep "current version" | head -1
otool -l SwiftSupport/iphoneos/libswiftUIKit.dylib | grep "current version" | head -1
```
and compare the line that mentions the library version

3. To get unsigned versions of swift library, you can take a look at 
```
/Applications/Xcode.app//Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos/
```

4. Remember that you should also have no extra files in either of the folders, if you have 21 swift files in Frameworks, you should have 21 files in swiftsupport.

**Comment by pwhsueh** [comment]
@nadalizadeh It works for me!! Thank you!!

**Comment by MasDevProject** [comment]
@pwhsueh @nadalizadeh 
Which version of XCode are you using?
Using 10.3 we got the same problem when publishing.

**Comment by EugeneUr** [comment]
A heads up for anyone dealing with deploying for iOS 13. It looks like the swift libraries have been updated and the Xamarin.Swift4.*.dll need to be updated as well.

After updating all the libraries, building the app and creating the archive. I used the following command to get the correct dylib into the app.

 `SWIFT_DLLS = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos"

run(["lipo", f"{SWIFT_DLLS}/{swift_lib}", "-remove", "arm64e", "-output", f"{swift_support_dir}/iphoneos/{swift_lib}"])`

**Comment by DrayTheFingerless** [comment]
> A heads up for anyone dealing with deploying for iOS 13. It looks like the swift libraries have been updated and the Xamarin.Swift4.*.dll need to be updated as well.
> 
> After updating all the libraries, building the app and creating the archive. I used the following command to get the correct dylib into the app.
> 
> `SWIFT_DLLS = "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift-5.0/iphoneos"
> 
> run(["lipo", f"{SWIFT_DLLS}/{swift_lib}", "-remove", "arm64e", "-output", f"{swift_support_dir}/iphoneos/{swift_lib}"])`

where do you run these commands? I've been pulling airs trying to fix this mess.

Also to what version do you update xamarin.swift?

**Comment by Flash3001** [comment]
@DrayTheFingerless you need to remove all Xamarin.Swift4 packages and use the latest Xamarin.Swift Nuget Package as it will copy the latest Swift libraries for you from Xcode.

Before publishing you need to run a script to include the a SwiftSupport folder in your IPA (https://github.com/Flash3001/ipa-packager) 

You can learn more about how everything works by reading this https://medium.com/@Flash3001/binding-swift-libraries-xamarin-ios-ff32adbc7c76 (Step 6 and 7)

**Comment by nininea1** [comment]
Hi there, 

does this solution still working ? I have vs 8.3.10 version and xcode Version 11.3.1 (11C504). 
after using ipa-packager  SwiftSupport is empty in my .ipa file ....   Any solution ? 
<img width="369" alt="Screen Shot 2020-04-14 at 2 38 27 PM" src="https://user-images.githubusercontent.com/43409661/79216079-a7c53900-7e5d-11ea-9154-f571149e1993.png">
