### ISSUE TITLE
Crashes on device, but works fine in Simulator

### ISSUE THREAD

**Issue by daffodilistic** [Flash3001/iOSCharts.Xamarin#28]
Hi,

I have a Xamarin Forms project which uses iOSCharts, everything works fine in Simulator, but when I test the project on device, it crashes. I am using the LineChartView as a custom renderer with Xamarin.Forms, and I inherited iOSCharts.LineChartView as a parent class:

```C#
// Custom subclass
public class LineChartView : iOSCharts.LineChartView
{
    public void SetHorizontalLabels(string[] formattedTime, string displayFormat)
    {
        this.XAxis.ValueFormatter = new MonthFormatter(formattedTime, displayFormat);
    }
}
```
And here is my ViewRenderer:
```C#
public class LineChartViewRenderer : ViewRenderer<StockPortfolio.LineChartView, LineChartView>, IGenericChart
{
        LineChartView nativeChart;

    protected override void OnElementChanged(ElementChangedEventArgs<StockPortfolio.LineChartView> e)
    {
        base.OnElementChanged(e);

        nativeChart = new LineChartView(this.Context);
        Element.chart = this;

        SetNativeControl(nativeChart);
    }

    public void SetHorizontalLabels(string[] labels, string displayFormat)
    {
        nativeChart.SetHorizontalLabels(labels, displayFormat);
    }
}
```
Here's the stacktrace: https://pastebin.com/CpyBiFHS

**Comment by Flash3001** [comment]
Hey @daffodilistic , this issue is the same as the one reported in here https://github.com/Flash3001/iOSCharts.Xamarin/issues/11 , but I wasn't able to fix it yet.

**Comment by Flash3001** [comment]
It seems it is not possible to subclass a Swift class. (https://stackoverflow.com/a/35244676/1698917).

The current solution is to do what proposed on #11  comments.
