### ISSUE TITLE
it must be clean when running app

### ISSUE THREAD

**Issue by suihanhbr** [Flash3001/iOSCharts.Xamarin#29]
I found it must be clean when running app , or it will be crash .

`Application 'com.iosui.runner' terminated.
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /private/var/containers/Bundle/Application/0017C66F-29B7-4C48-9D71-6A79561077E5/iOS_UIRunner.app/Frameworks/Charts.framework/Charts
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/0017C66F-29B7-4C48-9D71-6A79561077E5/iOS_UIRunner.app/Frameworks/libswiftCore.dylib: code signature invalid for '/private/var/containers/Bundle/Application/0017C66F-29B7-4C48-9D71-6A79561077E5/iOS_UIRunner.app/Frameworks/libswiftCore.dylib'`

**Comment by suihanhbr** [comment]
It said to set the EMBEDDED_CONTENT_CONTAINS_SWIFT to YES can fix this problem.but How can I set EMBEDDED_CONTENT_CONTAINS_SWIFT in xamarin studio? I can't find any entry to set this item.Thank you .

**Comment by Flash3001** [comment]
@suihanhbr Were you able to fix this issue?

Does it happens on Device or Simulator, both?
Which version of Charts and SwiftSupport are you using?
