### ISSUE TITLE
Radar Chart Implementation issue

### ISSUE THREAD

**Issue by muzamilhassan1987** [Flash3001/iOSCharts.Xamarin#30]
I am trying to implement Radar Chart 
I create the object of RadarChartView
then access the properties in my xamarin.ios CS class, but enable to acess any field of RadarChartView
like i am unable to access these fields
    _chartView.webLineWidth = 1.0;
    _chartView.innerWebLineWidth = 1.0;
    _chartView.webColor = UIColor.lightGrayColor;
How i will acheive this ?

**Comment by Flash3001** [comment]
@muzamilhassan1987 all these field are available through the same property, but with the first letter in uppercase.

_chartView.WebLineWidth = 1.0;
_chartView.InnerWebLineWidth = 1.0;
_chartView.WebColor = UIColor.lightGrayColor;
