### ISSUE TITLE
Bar Chart empty

### ISSUE THREAD

**Issue by Ruchita-Bora** [Flash3001/iOSCharts.Xamarin#36]
I am using iOSCharts 3.0.2 as I have Xcode 9.2. I am trying to plot bar chart. Following is the code. But with following code I am unable to view any bars. While debugging i see BarData as null. But there is no way I can set BarData as its read only property. Can you please guide me where I am going wrong. 

            var unitsSold = new double[] { 20.0, 4.0, 6.0, 3.0, 12.0, 16.0, 4.0, 18.0, 2.0, 4.0, 5.0, 4.0 };
            List<BarChartDataEntry> dataEntries = new List<BarChartDataEntry>();

            for (int i = 0; i < unitsSold.Length; i++)
            {
                BarChartDataEntry dataEntry = new BarChartDataEntry(i, unitsSold[i]);
                dataEntries.Add(dataEntry);
            }

            BarChartDataSet dataSet = new BarChartDataSet(dataEntries.ToArray(), "Units Sold");
            ChartData chartData = new ChartData(dataSet);
            barChartView.Data = chartData;
---
Thanks

**Comment by Flash3001** [comment]
Hey, 

To set the data to the ChartView you need to use a BarChartData instead of a ChartData class. 

Unfortunately that restriction is lost in the binding.

**Comment by Ruchita-Bora** [comment]
I am not able to set data to BarChartData. Since that is a read only property.

Also I am unable to use 3.0.4 version. I have xcode 9.2 on my machine. With 3.0.4 app launches and crashes immediately (after adding 3.0.4 nuget). So had to go to earlier version (3.0.2). And with 3.0.2  I am unable to set BarData since its read only property. Any solution?

**Comment by Flash3001** [comment]
@Ruchita-Bora What I mean is that BarChartData inherits from ChartData, so you can create a new BarChartData and set it where the CharData is requested in the view. Try this:

       BarChartData chartData = new BarChartData(dataSet);
       barChartView.Data = chartData;

**Comment by merckxite** [comment]
@Ruchita-Bora w.r.t your second question, the 3.0.4 package requires Swift 4, there is some information about this breaking change in the readme. Make sure you clear out all of your previous packages from your project before installing the new version. You can also try out the newer >3.1.1 packages but they will require Swift 4.1 (and Xcode 9.3). Let me know if you get it worked out.

**Comment by Ruchita-Bora** [comment]
Hi.. Tried to create BarChartData and setting it to Data as follows-

           BarChartDataSet dataSet = new BarChartDataSet(dataEntries.ToArray(), "Units Sold");
            BarChartData barChartData = new BarChartData(dataSet);
            ChartData chartData = new ChartData(dataSet);
            barChartView.Data = barChartData;

 When doing so it gives me error 
Cannot convert from 'iOSCharts.BarChartDataSet' to 'iOSCharts. IInterfaceChartDataSet[]'. Creating ChartData does not give me error but creating BarChartData does give me above mentioned error.

**Comment by Ruchita-Bora** [comment]
It worked!  Thanks for your help.
