### ISSUE TITLE
IValueFormatter could not be found

### ISSUE THREAD

**Issue by dickson95** [Flash3001/iOSCharts.Xamarin#39]
Hi
I am working in a chart for Xamarin iOS. I had use the MPandroidChart android binding for Xamarin and it is good. But, when I try to implement IValueFormatter interface it does not exist and get the following error "IValueFormatter could not be found". Which equivalent class is in iOS binding?

**Comment by merckxite** [comment]
Hi @dickson95,

I think what you're looking for is the interface `IInterfaceChartValueFormatter`, or alternatively the abstract class `InterfaceChartValueFormatter`. 

You can either implement or override the method `Entry(double value, ChartDataEntry entry, nint dataSetIndex, ChartViewPortHandler viewPortHandler)` as an alternative to MPAndroidChart's `GetFormattedValue(float value, Entry entry, int dataSetIndex, ViewPortHandler viewPortHandler)`.
