### ISSUE TITLE
Error ITMS-90668: "Invalid Bundle Executable". The executable file "aap/Frameworks/Charts.framework/Charts" contains incomplete  bitcode

### ISSUE THREAD

**Issue by deepakthumbmunkeys** [Flash3001/iOSCharts.Xamarin#4]
Hello,

   I'm facing this issue at the time of pulishing the app. It would be really helpful if you can do a build without bitcode or if you have any other suggestions please let me know

**Comment by Flash3001** [comment]
I'll release a new version as soon as I can without it. In meanwhile you can try using version 2.2.3.9, I've sent it without bitcode.

Version 2.2.4 is using the original binaries I've got from original library. Other user has managed to send version 2.2.4. 

Did you found a workaround?

**Comment by deepakthumbmunkeys** [comment]
@Flash3001 : Thanks ,  Actually I was trying  version 2.2.4 as mentioned in issue #3  but then I'm getting a new error : 

 Error Messages: ERROR ITMS-90635: "Invalid Mach-O Format. The Mach-O in bundle "MyApp/Frameworks/Charts.framework" isn’t consistent with the Mach-O in the main bundle. The main bundle Mach-O contains armv7(machine code) and arm64(machine code), while the nested bundle Mach-O contains armv7(bitcode and machine code) and arm64(bitcode and machine code). Verify that all of the targets for a platform have a consistent value for the ENABLE_BITCODE build setting."

**Comment by deepakthumbmunkeys** [comment]
Hi Flash

We tried every possible things to solve this issue but still not resolved. We're blocked in publishing the app. Can you please let us know that when you'll make a new build so that we can move further.

Thanks

**Comment by Flash3001** [comment]
@deepakthumbmunkeys I've just uploaded it to NuGet. Version 2.2.4.1

Please, give it a try and tell me if it worked.

**Comment by deepakthumbmunkeys** [comment]
@Flash3001  : I tried v-2.2.4.1 but still same error. any suggestion ??

**Comment by Flash3001** [comment]
@deepakthumbmunkeys If you are using Xamarin Studio, remove 'bin' and 'obj' folders and try again. 
If you are using Visual Studio try removing the same folders and on your Build Host the folder '~/Library/Caches/Xamarin/mtbs/build'. 

To check if there's any bitcode in your final App: Unarchive your 'IPA' file go to: '/Payload/YOUAPP.app/Frameworks/Charts.framework'. Open the terminal in this folder and run the command: 

`otool -l -arch armv7 Charts | grep LLVM`

If it return nothing, then it has no BITCODE. 

Please, try it in your current .app

**Comment by deepakthumbmunkeys** [comment]
@Flash3001  sorry for the above comment ....it's working now, thanks for help :)

**Comment by AdriDmgz** [comment]
Hello,

I'm having this problem again with version 2.2.5.1. It should be happening or maybe there is something wrong by my side? 

I have tried to delete obj and bin folders. Running the otool command returns nothing, but when I upload the .ipa it keeps telling these two errors:

`ERROR ITMS-90179: "Invalid Code Signing. The executable 'Payload/FQAppiOS.app/Frameworks/Charts.framework/Charts' must be signed with the certificate that is contained in the provisioning profile."
`  
`ERROR ITMS-90502: "Invalid Bundle. Apps that only contain the arm64 slice must also have 'arm64' in the list of UIRequiredDeviceCapabilities in Info.plist."`

Can you help me with this?

**Comment by Flash3001** [comment]
Your problem isn't related to the original Issue question. 

About the error ERROR ITMS-90179. How are you singing the app?
Were you able to sent the App to AppStore before?

Take a look in section 7 of this document:
http://stackoverflow.com/documentation/proposed/changes/70398
It's work in progress, but it show how to send the app to AppStore. 

ps: You could also give 2.2.4.1 a try. It works work for most people. So if it doesn't work we know its a problem on your side.

**Comment by AdriDmgz** [comment]
Oh, I thought it was the same problem, sorry. 

Yep, I already have a previous version of my app in the App Store, I've been sending versions before with no problem. In this version the only new feature is the charts sections where I'm using your library, downloaded with Xamarin Studio as a Nuget package. 

I'm creating the IPA with Xamarin Studio and sending it with the Application Loader 3.5 as usual. I've already tried to send it after generating a processed IPA with the Swift binding script, but the results are the same.

I'll do some more research and I'll try with 2.2.4.1 to see if that works for me. Thanks!

**Comment by AdriDmgz** [comment]
Please ignore me, I've just discovered that I was creating the IPA in debug instead of release (I didn't know it was possible at all). Now in release everything goes perfect, I even didn't have to run the Swift binding script to be able to upload the IPA.

**Comment by AdriDmgz** [comment]
Lying, I do have to run the Swift binding script, the IPA gets rejected after uploading it. But the other problem does not happen any more. Sorry for the inconvenience.
