### ISSUE TITLE
InvalidSwiftSupport - Again

### ISSUE THREAD

**Issue by felipecds** [Flash3001/iOSCharts.Xamarin#41]
Sorry for bothering you again with this question, but I'm trying to publish my app since yesterday and this infamous error keep coming from Apples validation.

I tried your ipa-archiver, the newest version from jamesbar2, tried manual copy and nothing I do solves this error. 

Sometimes its the folder that not exists, sometimes are invalid signatures.

On xcode's archive, it shows valid for my package, but when I upload to store this errors comes out.

What can I do?

**Comment by Flash3001** [comment]
Hey @felipecds, please share the exact error from Apple. There are more than one reason for the rejection. 

What version of SwiftSupport your app is using? What is the Xcode version installed in your build machine?

**Comment by felipecds** [comment]
@Flash3001 Thanks for replying. There are many of them, I will attach them here:

Using latest support version and xcode version from nuget/store

First e-mail response:

Invalid Swift Support - The files libswiftDarwin.dylib, libswiftFoundation.dylib, libswiftDispatch.dylib, libswiftObjectiveC.dylib, libswiftCoreAudio.dylib, libswiftCoreFoundation.dylib, libswiftCoreGraphics.dylib, libswiftCoreData.dylib, libswiftUIKit.dylib, libswiftQuartzCore.dylib, libswiftCoreMedia.dylib, libswiftCoreImage.dylib, libswiftCore.dylib, libswiftos.dylib, libswiftMetal.dylib don’t match /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftDarwin.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftFoundation.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftDispatch.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftObjectiveC.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreAudio.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreData.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftUIKit.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftQuartzCore.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreMedia.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreImage.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCore.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftos.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftMetal.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Don’t apply post-processing to /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftDarwin.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftFoundation.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftDispatch.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftObjectiveC.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreAudio.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreData.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftUIKit.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftQuartzCore.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreMedia.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCoreImage.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftCore.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftos.dylib, /Payload/CDSTarefas.Mobile.IOS.app/Frameworks/libswiftMetal.dylib. 

Second one:
Invalid Swift Support - The file libswiftCore.dylib doesn’t have the correct code signature. Make sure you’re using the correct signature, rebuild your app using the current public (GM) version of Xcode, and resubmit it. Don’t just modify the code signature of libswiftCore.dylib. 

Third one (after using ipa-archiver):
This bundle is invalid - Your archive contains paths that are not allowed: ( "Desktop" ) 

Forth one:
Invalid Swift Support - The file .DS_Store doesn’t have a signing ID. Sign the file, rebuild your app using the current public (GM) version of Xcode, and resubmit it.

**Comment by Flash3001** [comment]
How are you generating the app? Using VS4M, VS for Windows or a custom script? 

Before anything please check if the `.DS_Store` files are included in your .csproj, if they are please remove them.

If you happen to be using VS for Mac, try the following steps: 

1 - Set your project for Release configuration
2 - Right click your iOS project
3 - Select Archive for Publishing
4 - After the process is complete click **Sign and Distribute...**
5 - Select App Store and move forward - do not start the upload via Application Loader as VS will suggest. 
6 - When it is complete and the IPA is saved to a folder, extract it using any app so you can get access to the .app file - you can delete the original .ipa file.
7 - Run the original script (https://github.com/bq/ipa-packager) with a command similar to: `sh package_ipa.sh '/Users/flash/Desktop/Payload/SuasVendasIOS.app' '/Users/flash/Desktop/YS.Mobile.iOS.ipa'` (notice that only the .app is used as input and the .ipa is the output expected to be created - the final IPA will contain only 2 folders: Payload and SwiftSupport)
8 - Upload the newly created IPA to App Store.

ps: When doing it manually I usually just type `sh package_ipa.sh ` on the command line then drag and drop the .app file into it so I don't mistype the path - when you do it the full path is inserted into the command line. Then the same with the .ipa file - actually a totally new .ipa file is going to be created.

**Comment by felipecds** [comment]
Thnks for replying. I'm using VS for Mac for generating the .ipa file. 

I did your steps and send the .ipa file for apple. Waiting for response. I'll update the thread when they send me an e-mail.

EDIT:
They approved the files. Thanks for helping, thanks a lot.

**Comment by Flash3001** [comment]
Happy to help =)
