### ISSUE TITLE
XAxis value formatter not working

### ISSUE THREAD

**Issue by yero007** [Flash3001/iOSCharts.Xamarin#44]
Hello, 
The XAxis Value Formatter is set but the values on the chart are the numeric ones. While debugging I can see . the code gets the value and enters in the callback method but the data displayed on the graphics are still the numbers.
This is what I have used: mChart.XAxis.ValueFormatter = this; and the class implements the IInterfaceChartAxisValueFormatter interface.
Is there a workaround for this?

Thanks!

**Comment by Flash3001** [comment]
@yero007

I'm not sure what can be wrong in there. Do you mind to share a full sample? 

Here is working version I have (the Axis is not the same though):

```
                public class ReaisAxisFormater : NSObject, IInterfaceChartAxisValueFormatter
		{
			private readonly CultureInfo _culture = CultureHelper.GetNewCulture();

			public string Axis(double value, ChartAxisBase axis)
			{
				return string.Format(_culture, "{0:C}", value);
			}
		}
```

```
          if (_chart is BarLineChartViewBase c)
          {
               ....
                c.LeftAxis.ValueFormatter = new ReaisAxisFormater();
          }
```
