### ISSUE TITLE
Was Successfully able to upload the ipa in the Application Loader But got an Email from Apple iTunes Connect stating there are one or more issues 

### ISSUE THREAD

**Issue by amrutha786** [Flash3001/iOSCharts.Xamarin#45]
Invalid Swift Support - The files libswiftCoreFoundation.dylib, libswiftCoreGraphics.dylib, libswiftDarwin.dylib, libswiftUIKit.dylib, libswiftQuartzCore.dylib, libswiftFoundation.dylib, libswiftCoreImage.dylib, libswiftCore.dylib, libswiftObjectiveC.dylib, libswiftos.dylib, libswiftDispatch.dylib, libswiftMetal.dylib donâ€™t match /Payload/MyApp.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/MyApp.app/Frameworks/libswiftDarwin.dylib, /Payload/MyApp.app/Frameworks/libswiftUIKit.dylib, /Payload/MyApp.app/Frameworks/libswiftQuartzCore.dylib, /Payload/MyApp.app/Frameworks/libswiftFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreImage.dylib, /Payload/MyApp.app/Frameworks/libswiftCore.dylib, /Payload/MyApp.app/Frameworks/libswiftObjectiveC.dylib, /Payload/MyApp.app/Frameworks/libswiftos.dylib, /Payload/MyApp.app/Frameworks/libswiftDispatch.dylib, /Payload/MyApp.app/Frameworks/libswiftMetal.dylib. Make sure the files are correct, rebuild your app, and resubmit it. Donâ€™t apply post-processing to /Payload/MyApp.app/Frameworks/libswiftCoreFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreGraphics.dylib, /Payload/MyApp.app/Frameworks/libswiftDarwin.dylib, /Payload/MyApp.app/Frameworks/libswiftUIKit.dylib, /Payload/MyApp.app/Frameworks/libswiftQuartzCore.dylib, /Payload/MyApp.app/Frameworks/libswiftFoundation.dylib, /Payload/MyApp.app/Frameworks/libswiftCoreImage.dylib, /Payload/MyApp.app/Frameworks/libswiftCore.dylib, /Payload/MyApp.app/Frameworks/libswiftObjectiveC.dylib, /Payload/MyApp.app/Frameworks/libswiftos.dylib, /Payload/MyApp.app/Frameworks/libswiftDispatch.dylib, /Payload/MyApp.app/Frameworks/libswiftMetal.dylib.

Xcode: 9.4.1 

Visual Studio : 7.6.9 (Build 22) 

Added Xamarin.Swift4 Packages.

**Comment by Flash3001** [comment]
Hey @amrutha786, 

Please read this https://github.com/Flash3001/Xamarin.Swift3.Support#takeaways
