### ISSUE TITLE
CandleStick Chart is not showing up within a CombinedChart on the latest release of 3.2.0

### ISSUE THREAD

**Issue by mister-giga** [Flash3001/iOSCharts.Xamarin#46]
This issue was in the original charts implementation of swift but it was resolved as stated on the issue of that repo
https://github.com/danielgindi/Charts/issues/3673

**Comment by Flash3001** [comment]
Thank you for reporting it @mister-giga. I'll update the project and update the Nuget package.

**Comment by Flash3001** [comment]
@mister-giga That fix is on master branch, but it is not on their 3.2.1 release.

https://github.com/danielgindi/Charts/compare/v3.2.1...master

The Nuget package is following the original Charts library releases. I suppose there will be another one soon as there is a new Xcode version and usually a point release is done when that happens.

**Comment by mister-giga** [comment]
Oh sorry. Thanks for info and for this great binding that helped me many times saving time!

**Comment by Flash3001** [comment]
@mister-giga this issue was fixed on 3.2.2. The binding is updated and available on Nuget. It now depends on Swift 5.
