### ISSUE TITLE
upload to appstore issue

### ISSUE THREAD

**Issue by alisterk** [Flash3001/iOSCharts.Xamarin#48]
hello, im using vs for mac 7.7.2 and xcode 10.1(10B61).
and ioschart.xamarin version was 3.2.1

the process  step is: 
1. vs formac -> build at Release on iphone -> Archive for Publishing
2. Sign and Distribute -> for appstore
3. use Application Loader upload to appstore
then the errlog as blow : 

```
information on the iOS app bundle structure."
		ERROR ITMS-90171: "Invalid Bundle Structure - The binary file 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftUIKit.dylib' is not permitted. Your app can’t contain standalone executables or libraries, other than a valid CFBundleExecutable of supported bundles. Refer to the Bundle Programming Guide at https://developer.apple.com/go/?id=bundle-structure for information on the iOS app bundle structure."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCore.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreAudio.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreData.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreFoundation.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreGraphics.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreImage.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreMedia.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftDarwin.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftDispatch.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftFoundation.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftMetal.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftObjectiveC.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftQuartzCore.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftUIKit.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
		ERROR ITMS-90209: "Invalid Segment Alignment. The app binary at 'AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftos.dylib' does not have proper segment alignment. Try rebuilding the app with the latest Xcode version."
```

and i also using  script from https://github.com/bq/ipa-packager ,
but the same error log.

any could help?

==============================

and then i found those logs by building :
 

>  target _CopyResourcesToBundle:
>  Creating directory '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCore.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCore.dylib'
>     Creating directory '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCore.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCore.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCoreAudio.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreAudio.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCoreAudio.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCoreAudio.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCoreData.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreData.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCoreData.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCoreData.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCoreFoundation.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCoreFoundation.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCoreFoundation.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreFoundation.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCoreGraphics.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCoreGraphics.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCoreGraphics.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreGraphics.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCoreImage.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCoreImage.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCoreImage.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreImage.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftCoreMedia.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftCoreMedia.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftCoreMedia.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftCoreMedia.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftDarwin.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftDarwin.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftDarwin.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftDarwin.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftDispatch.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftDispatch.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftDispatch.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftDispatch.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftFoundation.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftFoundation.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftFoundation.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftFoundation.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftMetal.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftMetal.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftMetal.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftMetal.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftObjectiveC.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftObjectiveC.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftObjectiveC.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftObjectiveC.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftos.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftos.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftos.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftos.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftQuartzCore.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftQuartzCore.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftQuartzCore.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftQuartzCore.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/Frameworks/libswiftUIKit.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/Frameworks/libswiftUIKit.dylib'
>     Copying file from '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/obj/iPhone/Release/SwiftFrameworksSimulator/libswiftUIKit.dylib' to '/Users/rocky/Projects/gitee/afors/AFORS.APP/AFORS.APP/src/AFORS.APP.iOS/bin/iPhone/Release/AFORS.APP.iOS.app/SwiftFrameworksSimulator/libswiftUIKit.dylib'
>  

that same as the  Xamarin.Swift4.targets not working or some issue .
and the published .ipa file still contain the  SwiftFrameworksSimulator folder.
anyone could help???
thanks a lot.

**Comment by alisterk** [comment]
and then i  manual steps : 
1. archive in vs for mac , 
2. open archive in finder ,and right click  the .xcarchive file ,then click 'show content' .
3. into  Procucts->Applications ,then right click the package and 'show content' into app folder
4. find the 'SwiftFrameworksSimulator' folder ,and delete it.
5. back to  vs for mac,   Sign and Distribute -> for appstore,save the ipa file to disk.
6. unpack the ipa file , then run  script from https://github.com/bq/ipa-packager 
6. use Application Loader upload the repack ipa file  to appstore

now it can be upload to appstore ,but  It is not clear what other problems are there.
i'll update  if any result back.

**Comment by Flash3001** [comment]
@alisterk This issue is exactly the same issue you are having related to not being able to run on Simulator. I've added a comment to https://github.com/Flash3001/iOSCharts.Xamarin/issues/47#issuecomment-452548254 . That temporary fix will fix this issue as well.

**Comment by alisterk** [comment]
thanks a lot for your help ! great job!!!
