### ISSUE TITLE
“Invalid Swift Support” in Xamarin.iOS

### ISSUE THREAD

**Issue by jamesbar2** [Flash3001/iOSCharts.Xamarin#5]
Thanks for your work on this, it works great until I try to export it to iTunes Connect.  I know you address the issue on the Readme; however, for some reason that doesn't seem to work.

I've opened a StackOverflow issue, but haven't been able to find an appropriate workaround yet.  [Here is the link to StackOverflow](http://stackoverflow.com/questions/37820300/invalid-swift-support-using-native-swift-library-in-xamarin-ios). 

Let me know if you have any ideas on how to remedy this issue; hoepfully, I'm not just using the tool you suggested incorrectly.

Thanks in advance.

**Comment by Flash3001** [comment]
What's your Xcode version? Make sure to be using the latest and GM one, I believe it to be 7.3. The script described on the Readme copy the files from Xcode folder.  

If you unpack the IPA created after the script ran you can check for the folder's existence.

**Comment by jamesbar2** [comment]
My version is 7.3.1.  I'll give it another shot, and get back to you.

**Comment by Flash3001** [comment]
I send my app using Application Loader.

**Comment by jamesbar2** [comment]
Out of curiosity, if you recompile the Charts.framework with the "EMBEDDED_CONTENT_CONTAINS_SWIFT" option set to YES.  Do you think doing that might trick it into doing the right thing?

I was trying it earlier, but keep getting errors (partially because I have no ideas how the .framework is imported).

**Comment by Flash3001** [comment]
I'll close the issue as you managed to publish it.

http://stackoverflow.com/questions/37820300/invalid-swift-support-using-native-swift-library-in-xamarin-ios?answertab=votes#tab-top

**Comment by jamesbar2** [comment]
@Flash3001 I've created a Github for a new library that makes this much simpler.  All you need to do is give it the exported IPA and it will do all the fixing for you and pop out the new one.  Here's the link: https://github.com/jamesbar2/auto-ipa-packager

**Comment by Flash3001** [comment]
@jamesbar2 That's nice! Thanks
