### ISSUE TITLE
Support for xCode 11

### ISSUE THREAD

**Issue by AndaBucsa** [Flash3001/iOSCharts.Xamarin#53]
Hi guys, 
Wondering if you are working on adding support for xCode 11?

**Comment by Flash3001** [comment]
Hey @AndaBucsa it does already work with Xcode 11. 

Before Swift 5 was released we had to update the library for every new Xcode version. That is not necessary anymore with Swift 5 =) 

I am using Xcode 11.4 to compile my projects and it works perfect.c
