### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hartra344** [Flash3001/iOSCharts.Xamarin#7]
Is it possible to add a license file on here and Nuget. I work at Microsoft and we'd love to use your bindings but legal isn't allowing it because of the lack of a license.

**Comment by Flash3001** [comment]
Done!

Added the same as the original library. Also sent it to Nuget.

I suppose you also need it in dependencies. So I added the license to https://github.com/Flash3001/Xamarin.Swift22.Support as well.

**Comment by hartra344** [comment]
Thank You!
