### ISSUE TITLE
Issue setting ChartMarkerView to LineChartView

### ISSUE THREAD

**Issue by Chico741** [Flash3001/iOSCharts.Xamarin#9]
It is not possible to add a **ChartMarkerView** to **LineChartView.Marker**. Shouldn't **LineChartView.Marker** be of type **IInterfaceChartMarker** instead of **InterfaceChartMarker** or **InterfaceChartMarker** the parent class of **ChartMarkerView**?

![bildschirmfoto 2016-10-25 um 10 12 34](https://cloud.githubusercontent.com/assets/5487049/19677874/9f0e94f4-9a9b-11e6-81e0-bfa19b9e8b31.png)

**Comment by Flash3001** [comment]
@Chico741 Is it related to the newer 3.0 version?

**Comment by Flash3001** [comment]
@Chico741 It was really wrong! I'm sorry for that. 

Just pushed an updated to NuGet.

**Comment by Chico741** [comment]
@Flash3001 Thank you very much, just updated and it works like expected. 👍
